# configs/example_pov_small_px_cnn_vit.yaml
# PPO on pixel POV grid with CNN->ViT hybrid feature extractor

run:
  name: snake_ppo_cnn_vit
  seed: 42
  num_envs: 16
  total_timesteps: 100_000_000
  checkpoint_freq: 250_000
  resume_checkpoint: null

level:
  height: 7
  width: 12
  food_count: 1

env:
  id: pov_pixel
  params:
    view_radius: 5

observation:
  frame_stack:
    n_frames: 1

model:
  features_extractor:
    type: px_cnn_vit
    features_dim: 64
    params:
      cnn_stem: px_tilealign_cnn_c4
      c_mult: 1

      # ViT part
      d_model: 64
      n_layers: 2
      n_heads: 2
      dropout: 0.0
      use_cls_token: true
      use_2d_positional: true

  net_arch: [32]


ppo:
  n_steps: 2048
  batch_size: 128
  n_epochs: 2
  gamma: 0.999
  ent_coef: 0.03
  learning_rate: 1e-4

#  gae_lambda: 0.95
#  clip_range: 0.1
#  vf_coef: 0.5
#  max_grad_norm: 0.5
#  target_kl: 0.1
  normalize_advantage: true

  verbose: 0

eval:
  intermediate:
    enabled: true
    episodes: 100
    deterministic: true
    seed_offset: 10_000

  final:
    enabled: true
    episodes: 1000
    deterministic: true
    seed_offset: 20_000
